-- GalaxyTrader MK3 Diagnostic Report Display
-- Shows the exhaustive diagnostic report generated by gt_context_diagnose.xml
-- in a scrollable popup frame.
--
-- Uses GT_UI library (gt_ui_library.lua) for all table/row/button helpers.
--
-- Data transfer: MD serializes the report as a delimited string stored on
-- player.entity.$GT_DiagReport.  Format:
--   Sections separated by "@@"
--   Rows separated by ";;"
--   Fields separated by "||"
--   First element of each section chunk is the section name (no field separators)
--   Subsequent elements: STATUS||CHECK||DETAIL

-- FFI setup
local ffi = require("ffi")
local C = ffi.C
ffi.cdef[[
    typedef uint64_t UniverseID;
    UniverseID GetPlayerID(void);
]]

local menu = Helper.getMenu("MapMenu")
if not menu then
    DebugError("[GT Diagnose] MapMenu not found - diagnostic display will not be available")
    return
end

-- Verify GT_UI library is loaded
if not GT_UI then
    DebugError("[GT Diagnose] ERROR: GT_UI library not loaded - check ui.xml load order")
    return
end

-- Diagnostic report state
local gtDiagnose = {
    sections    = {},   -- { { name=string, rows={ {status, check, detail}, ... } }, ... }
    shipId      = "",
    shipName    = "",
    timestamp   = 0,
    currentTab  = 1,    -- Currently selected section index (1-based)
    currentPage = 1,    -- Current page for paginated sections
    frameWidth  = 0,
    frameHeight = 0,
}

-- =============================================================================
-- REPORT PARSING
-- =============================================================================

function gtDiagnose.parseReport()
    local playerId = ConvertStringTo64Bit(tostring(C.GetPlayerID()))

    local reportStr   = GetNPCBlackboard(playerId, "$GT_DiagReport")
    gtDiagnose.shipId   = GetNPCBlackboard(playerId, "$GT_DiagShipId") or "???"
    gtDiagnose.shipName = GetNPCBlackboard(playerId, "$GT_DiagShipName") or "Unknown"
    gtDiagnose.timestamp = GetNPCBlackboard(playerId, "$GT_DiagTimestamp") or 0

    if not reportStr or reportStr == "" then
        DebugError("[GT Diagnose] No report data found on blackboard")
        return false
    end

    DebugError(string.format("[GT Diagnose] Report string length: %d, ship: %s",
        #reportStr, gtDiagnose.shipId))

    -- Parse sections (separated by "@@")
    local sectionChunks = GT_UI.split(reportStr, "@@")
    gtDiagnose.sections = {}

    for _, chunk in ipairs(sectionChunks) do
        local rowParts = GT_UI.split(chunk, ";;")
        if #rowParts > 0 then
            local section = {
                name    = rowParts[1],
                rows    = {},
                numCols = 3,  -- default: Status | Check | Detail
            }
            for i = 2, #rowParts do
                local fields = GT_UI.split(rowParts[i], "||")
                if #fields >= 6 then
                    -- 6-column structured row (Pair Details / Clearance)
                    table.insert(section.rows, {
                        status = fields[1] or "INFO",
                        check  = fields[2] or "",
                        detail = fields[3] or "",
                        col4   = fields[4] or "",
                        col5   = fields[5] or "",
                        col6   = fields[6] or "",
                    })
                    if section.numCols < 6 then
                        section.numCols = 6
                    end
                elseif #fields >= 3 then
                    table.insert(section.rows, {
                        status = fields[1] or "INFO",
                        check  = fields[2] or "",
                        detail = fields[3] or "",
                    })
                elseif #fields == 2 then
                    table.insert(section.rows, {
                        status = fields[1] or "INFO",
                        check  = fields[2] or "",
                        detail = "",
                    })
                end
            end
            table.insert(gtDiagnose.sections, section)
        end
    end

    DebugError(string.format("[GT Diagnose] Parsed %d sections", #gtDiagnose.sections))
    return #gtDiagnose.sections > 0
end

-- =============================================================================
-- FRAME LIFECYCLE
-- =============================================================================

function gtDiagnose.openReport(component)
    DebugError("[GT Diagnose] openReport called")

    if not gtDiagnose.parseReport() then
        DebugError("[GT Diagnose] ERROR: Could not parse report data")
        return
    end

    -- Show Ship State tab first (contains VERDICT at top)
    gtDiagnose.currentTab  = 1
    gtDiagnose.currentPage = 1

    -- Frame dimensions
    local frameWidth  = math.min(Helper.viewWidth * 0.85, Helper.scaleX(1400))
    local frameHeight = math.min(Helper.viewHeight * 0.85, Helper.scaleY(900))
    gtDiagnose.frameWidth  = frameWidth
    gtDiagnose.frameHeight = frameHeight

    -- Center on screen
    local xpos = (Helper.viewWidth - frameWidth) / 2
    local ypos = (Helper.viewHeight - frameHeight) / 2

    menu.contextMenuMode = "gt_diagnose"
    menu.contextMenuData = {
        component = component,
        xoffset   = xpos,
        yoffset   = ypos,
        width     = frameWidth,
    }

    gtDiagnose.createAndDisplayFrame()
end

function gtDiagnose.createAndDisplayFrame()
    local contextLayer = 2
    Helper.removeAllWidgetScripts(menu, contextLayer)

    menu.contextFrame = Helper.createFrameHandle(menu, {
        x                     = menu.contextMenuData.xoffset,
        y                     = menu.contextMenuData.yoffset,
        width                 = gtDiagnose.frameWidth,
        height                = gtDiagnose.frameHeight,
        layer                 = contextLayer,
        standardButtons       = { close = true },
        closeOnUnhandledClick = false,
    })
    menu.contextFrame:setBackground("solid", { color = GT_UI.COLORS.frameBg })

    gtDiagnose.populateFrame(menu.contextFrame)
    menu.contextFrame:display()
end

-- =============================================================================
-- FRAME CONTENT
-- =============================================================================

function gtDiagnose.populateFrame(frame)
    local sections = gtDiagnose.sections
    if #sections == 0 then return end

    local width = gtDiagnose.frameWidth - 2 * Helper.borderSize

    -- ===== TITLE BAR =====
    local titleTable = frame:addTable(1, {
        tabOrder         = 0,
        x                = Helper.borderSize,
        y                = Helper.borderSize,
        width            = width,
        highlightMode    = "off",
        reserveScrollBar = false,
    })
    local titleRow = titleTable:addRow(nil, {
        fixed   = true,
        bgColor = GT_UI.COLORS.headerBg,
    })
    titleRow[1]:createText(
        string.format("MK3 Diagnostic Report: %s (%s)",
            tostring(gtDiagnose.shipName), tostring(gtDiagnose.shipId)),
        {
            halign   = "center",
            font     = Helper.headerRow1Font,
            fontsize = Helper.headerRow1FontSize,
        }
    )
    local titleHeight = Helper.headerRow1FontSize + 10

    -- ===== TAB BAR =====
    -- Sections in natural order (Ship State first, contains VERDICT at top)
    local numSections = #sections
    local tabDefs = {}
    for i = 1, numSections do
        tabDefs[i] = { name = sections[i].name, sectionIdx = i }
    end

    local _, tabHeight = GT_UI.createTabBar(frame, tabDefs, gtDiagnose.currentTab, {
        x       = Helper.borderSize,
        y       = titleHeight + Helper.borderSize + 4,
        width   = width,
        maxTabs = 14,
        onClick = function(sectionIdx)
            gtDiagnose.currentTab  = sectionIdx
            gtDiagnose.currentPage = 1
            gtDiagnose.createAndDisplayFrame()
        end,
    })

    local contentY = titleHeight + tabHeight + Helper.borderSize + 8

    -- ===== CONTENT TABLE =====
    local currentSection = sections[gtDiagnose.currentTab]
    if not currentSection then
        gtDiagnose.currentTab = 1
        currentSection = sections[1]
    end
    if not currentSection then return end

    local allRows   = currentSection.rows or {}
    local totalRows = #allRows
    local numCols   = currentSection.numCols or 3

    -- Pagination
    local pageInfo = GT_UI.paginate(totalRows, gtDiagnose.currentPage)
    gtDiagnose.currentPage = pageInfo.currentPage  -- clamp

    -- Large sections: smaller font, no wordwrap (prevents X4 min-height crash)
    local detailFontSize = GT_UI.DEFAULTS.fontSize * 0.9
    local useWordWrap    = true
    if pageInfo.isPaginated then
        detailFontSize = GT_UI.DEFAULTS.fontSize * 0.75
        useWordWrap    = false
    end

    -- Determine section name for layout selection
    local sectionName = currentSection.name or ""
    local isPairDetails    = (sectionName == "Pair Details")
    local isClearance      = (sectionName == "Clearance")
    local isSearchSummary  = (sectionName == "Search Summary")
    local isReservations   = (sectionName == "Reservations and Fleet")
    local isMinerScan      = (sectionName == "Miner Resource Scan")
    local isMultiCol       = (numCols >= 6) or isPairDetails or isClearance or isSearchSummary or isMinerScan

    if isMultiCol then
        -- ===== 6-COLUMN STRUCTURED LAYOUT =====
        -- Pair Details: Status | Ware | Buy From | Sell To | Profit/ROI | Reason
        -- Clearance:    Status | Ware | Station  | Price   | Revenue    | Reason
        local contentTable = GT_UI.createScrollTable(frame, 6, {
            tabOrder         = 2,
            x                = Helper.borderSize,
            y                = contentY,
            width            = width,
            maxVisibleHeight = gtDiagnose.frameHeight - contentY - Helper.borderSize - 10,
        })
        -- Column headers depend on section type
        if isSearchSummary then
            -- Search Summary: Status=6%, Check=25%, Sell=10%, Buy=10%, Total=10%, rest=flexible
            GT_UI.setColPercents(contentTable, { 6, 25, 10, 10, 10 })
            GT_UI.addHeaderRow(contentTable, {
                { text = "Status", halign = "center" },
                "Sector / Check",
                { text = "Sell", halign = "right" },
                { text = "Buy", halign = "right" },
                { text = "Total", halign = "right" },
                "",
            })
        elseif isReservations then
            -- Reservations: Status=7%, Entry=18%, Ship/Detail=30%, Ware=15%, Info=14%, Extra=flexible
            GT_UI.setColPercents(contentTable, { 7, 18, 30, 15, 14 })
            GT_UI.addHeaderRow(contentTable, {
                { text = "Status", halign = "center" },
                "Entry",
                "Ship / Detail",
                "Ware",
                "Info",
                "Extra",
            })
        elseif isPairDetails then
            -- Pair Details: Status=6%, Ware=10%, Route=30%, Profit=12%, ROI=8%, Reason=flexible
            GT_UI.setColPercents(contentTable, { 6, 10, 30, 12, 8 })
            GT_UI.addHeaderRow(contentTable, {
                { text = "Status", halign = "center" },
                "Ware",
                "Route",
                { text = "Profit", halign = "right" },
                { text = "ROI", halign = "right" },
                "Reason",
            })
        elseif isClearance then
            GT_UI.addHeaderRow(contentTable, {
                { text = "Status", halign = "center" },
                "Ware",
                "Station (Sector)",
                "Price/Demand",
                { text = "Revenue", halign = "right" },
                "Reason",
            })
        elseif isMinerScan then
            -- Miner Resource Scan (dedicated self-scan):
            -- Status=6%, Ware=20%, Best Yield=10%, Reachable=10%, Sectors=10%, Notes=flexible
            GT_UI.setColPercents(contentTable, { 6, 20, 10, 10, 10 })
            GT_UI.addHeaderRow(contentTable, {
                { text = "Status", halign = "center" },
                "Ware (* = active)",
                { text = "Best Yield", halign = "right" },
                { text = "Reachable", halign = "center" },
                { text = "Sectors", halign = "right" },
                "Notes",
            })
        else
            GT_UI.addHeaderRow(contentTable, {
                { text = "Status", halign = "center" },
                "Col 1", "Col 2", "Col 3", "Col 4", "Col 5",
            })
        end

        -- Pagination header
        GT_UI.addPaginationHeader(contentTable, pageInfo, 6)

        -- Data rows
        if totalRows == 0 then
            GT_UI.addEmptyRow(contentTable, "No data in this section.", 6)
        else
            for i = pageInfo.startIdx, pageInfo.endIdx do
                local row = allRows[i]
                if not row then break end

                local status    = row.status or "INFO"
                local check     = row.check or ""
                local detail    = row.detail or ""
                local col4      = row.col4 or ""
                local col5      = row.col5 or ""
                local col6      = row.col6 or ""

                local statusColor = GT_UI.getStatusColor(status)

                -- Separator rows (check starts with "---")
                local isSeparator = (string.sub(check, 1, 3) == "---")
                local rowBg = isSeparator and GT_UI.COLORS.headerBg or nil

                -- For 3-field rows within a 6-col section (e.g. summary rows),
                -- span the detail across remaining columns
                if not row.col4 then
                    GT_UI.addDataRow(contentTable, {
                        { text = status, halign = "center", fontsize = detailFontSize, color = statusColor },
                        { text = check, fontsize = detailFontSize },
                        { text = detail, fontsize = detailFontSize, colSpan = 4,
                          color = (status == "FAIL") and GT_UI.COLORS.textNegative or nil },
                    }, { bgColor = rowBg })
                else
                    -- Right-align numeric columns per section type
                    local detailAlign = "left"
                    local col4Align   = "left"
                    local col5Align   = "right"
                    if isSearchSummary then
                        detailAlign = "right"
                        col4Align   = "right"
                    elseif isPairDetails then
                        col4Align = "right"
                    elseif isMinerScan then
                        -- Miner Resource Scan: Best Yield right, Reachable centered, Sectors right
                        detailAlign = "right"
                        col4Align   = "center"
                        col5Align   = "right"
                    end

                    GT_UI.addDataRow(contentTable, {
                        { text = status, halign = "center", fontsize = detailFontSize, color = statusColor },
                        { text = check, fontsize = detailFontSize },
                        { text = detail, halign = detailAlign, fontsize = detailFontSize },
                        { text = col4, halign = col4Align, fontsize = detailFontSize },
                        { text = col5, halign = col5Align, fontsize = detailFontSize },
                        { text = col6, fontsize = detailFontSize,
                          color = (status == "FAIL") and GT_UI.COLORS.textNegative or nil },
                    }, { bgColor = rowBg })
                end
            end
        end

        -- Pagination nav (needs 3+ columns, we have 6)
        -- Put prev in col1, indicator in col3, next in col6 for spacing
        if pageInfo.isPaginated and pageInfo.totalPages > 1 then
            local navRow = contentTable:addRow(true, {
                fixed   = true,
                bgColor = GT_UI.COLORS.headerBg,
            })

            if pageInfo.currentPage > 1 then
                GT_UI.createButton(navRow[1], "<<", {
                    bgColor  = GT_UI.COLORS.tabInactiveBg,
                    fontSize = detailFontSize,
                    onClick  = function()
                        gtDiagnose.currentPage = gtDiagnose.currentPage - 1
                        gtDiagnose.createAndDisplayFrame()
                    end,
                })
            else
                navRow[1]:createText("", {})
            end

            navRow[2]:createText("", {})
            navRow[3]:createText(
                string.format("Page %d / %d", pageInfo.currentPage, pageInfo.totalPages),
                { halign = "center", fontsize = detailFontSize }
            )
            navRow[4]:createText(
                string.format("(%d rows total)", pageInfo.totalRows),
                { halign = "center", fontsize = detailFontSize }
            )
            navRow[5]:createText("", {})

            if pageInfo.currentPage < pageInfo.totalPages then
                GT_UI.createButton(navRow[6], ">>", {
                    bgColor  = GT_UI.COLORS.tabInactiveBg,
                    fontSize = detailFontSize,
                    onClick  = function()
                        gtDiagnose.currentPage = gtDiagnose.currentPage + 1
                        gtDiagnose.createAndDisplayFrame()
                    end,
                })
            else
                navRow[6]:createText("", {})
            end
        end

        -- Footer
        GT_UI.addFooterRow(contentTable,
            string.format("Report at game time %.0fs  |  %d rows  |  %d sections total",
                gtDiagnose.timestamp or 0, totalRows, #sections),
            6)
    else
        -- ===== 3-COLUMN STANDARD LAYOUT =====
        local contentTable = GT_UI.createScrollTable(frame, 3, {
            tabOrder         = 2,
            x                = Helper.borderSize,
            y                = contentY,
            width            = width,
            maxVisibleHeight = gtDiagnose.frameHeight - contentY - Helper.borderSize - 10,
        })
        GT_UI.setColPercents(contentTable, { 22, 8 })  -- col 3 flexible

        -- Column headers
        GT_UI.addHeaderRow(contentTable, { "Check", "Status", "Detail" })

        -- Pagination header
        GT_UI.addPaginationHeader(contentTable, pageInfo, 3)

        -- Data rows (current page only)
        if totalRows == 0 then
            GT_UI.addEmptyRow(contentTable, "No data in this section.", 3)
        else
            for i = pageInfo.startIdx, pageInfo.endIdx do
                local row = allRows[i]
                if not row then break end

                local checkName = row.check or "?"
                local status    = row.status or "INFO"
                local detail    = row.detail or ""

                local statusColor = GT_UI.getStatusColor(status)

                -- Separator rows (check starts with "---")
                local isSeparator = (string.sub(checkName, 1, 3) == "---")
                local rowBg = isSeparator and GT_UI.COLORS.headerBg or nil

                GT_UI.addDataRow(contentTable, {
                    { text = checkName, fontsize = detailFontSize, wordwrap = false },
                    { text = status, halign = "center", fontsize = GT_UI.DEFAULTS.fontSize * 0.85, color = statusColor },
                    { text = detail, fontsize = detailFontSize, wordwrap = useWordWrap,
                      color = (status == "FAIL") and GT_UI.COLORS.textNegative or nil },
                }, { bgColor = rowBg })
            end
        end

        -- Pagination nav buttons
        GT_UI.addPaginationNav(contentTable, pageInfo, function(newPage)
            gtDiagnose.currentPage = newPage
            gtDiagnose.createAndDisplayFrame()
        end)

        -- Footer
        GT_UI.addFooterRow(contentTable,
            string.format("Report at game time %.0fs  |  %d rows  |  %d sections total",
                gtDiagnose.timestamp or 0, totalRows, #sections),
            3)
    end
end

-- =============================================================================
-- MENU HOOKS
-- =============================================================================

local origCreateCtx = menu.createContextFrame
menu.createContextFrame = function(width, height, xoffset, yoffset, noborder, startanimation, ...)
    if menu.contextMenuMode == "gt_diagnose" then
        return menu.contextFrame
    end
    if origCreateCtx then
        return origCreateCtx(width, height, xoffset, yoffset, noborder, startanimation, ...)
    end
end

local origRefreshCtx = menu.refreshContextFrame
menu.refreshContextFrame = function(setrow, setcol, noborder, ...)
    if menu.contextMenuMode == "gt_diagnose" then
        if menu.contextFrame then
            menu.contextFrame:display()
        end
        return
    end
    if origRefreshCtx then
        origRefreshCtx(setrow, setcol, noborder, ...)
    end
end

-- =============================================================================
-- EVENT REGISTRATION
-- =============================================================================

RegisterEvent("gt.openDiagnoseReport", function(_, component)
    DebugError("[GT Diagnose] Lua: Event gt.openDiagnoseReport received")

    if component then
        local component64 = ConvertIDTo64Bit(component)
        DebugError(string.format("[GT Diagnose] Lua: Component converted: %s", tostring(component64)))
        if component64 and component64 ~= 0 then
            gtDiagnose.openReport(component64)
        end
    else
        DebugError("[GT Diagnose] Lua: No component - opening anyway")
        gtDiagnose.openReport(nil)
    end
end)

DebugError("[GT Diagnose] Diagnostic report display loaded (using GT_UI library)")
